name: Quality CI

on:
  push:
    branches: ["main", "feature/**"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - run: npm ci
      - run: npm run build:prod --if-present
      - run: npm run coverage

      - uses: actions/upload-artifact@v4
        with:
          name: frontend_coverage_report
          path: ./frontend/coverage/frontend/

  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: ./backend
        run: mvn clean verify

  sonar:
    name: Sonar Analysis
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # récupérer coverage frontend
      - name: Download frontend coverage
        uses: actions/download-artifact@v4
        with:
          name: frontend_coverage_report
          path: frontend/coverage/frontend
          
      # setup java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # recompile backend
      - name: Build backend
        working-directory: ./backend
        run: mvn clean verify

      - name: Copy dependencies
        working-directory: ./backend
        run: mvn dependency:copy-dependencies -DoutputDirectory=target/dependency

      # sonar
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=epitaProjectFullStack_Projet_full_stack_epita
            -Dsonar.organization=epitaprojectfullstack
            -Dsonar.sources=backend/src/main/java
            -Dsonar.tests=backend/src/test/java
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
            -Dsonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
            -Dsonar.java.binaries=backend/target/classes
            -Dsonar.java.libraries=backend/target/dependency/*.jar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}